name: Docker Build and Push

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: abdulqudoos12
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: abdulqudoos12/cafe-management-system
        
    - name: Build and push API Gateway
      uses: docker/build-push-action@v4
      with:
        context: ./api-gateway
        push: true
        tags: abdulqudoos12/cafe-api-gateway:latest
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push Menu Service
      uses: docker/build-push-action@v4
      with:
        context: ./menu-services
        push: true
        tags: abdulqudoos12/cafe-menu-service:latest
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push Order Service
      uses: docker/build-push-action@v4
      with:
        context: ./order-services
        push: true
        tags: abdulqudoos12/cafe-order-service:latest
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push Payment Service
      uses: docker/build-push-action@v4
      with:
        context: ./payment-services
        push: true
        tags: abdulqudoos12/cafe-payment-service:latest
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push Inventory Service
      uses: docker/build-push-action@v4
      with:
        context: ./inventory-services
        push: true
        tags: abdulqudoos12/cafe-inventory-service:latest
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Build and push Customer Service
      uses: docker/build-push-action@v4
      with:
        context: ./customer-services
        push: true
        tags: abdulqudoos12/cafe-customer-service:latest
        labels: ${{ steps.meta.outputs.labels }} 